### PR TITLE
Fixing Travis

### PR DESCRIPTION
**Pull request by Ananthavijay**
Fixes https://github.com/cerebro-iiitv/cerebro-flutter/issues/3

- The error occured because there was no rakefile
- This PR will create a Rakefile with a simple task and thus making the build "passing"
- Check the [readme](https://github.com/Ananthavijay/cerebro-flutter/blob/master/README.md) in my repo  
- You can see the travis badge changed from  ``build unkown`` to ``build passing``

Thanks,
Anantha Vijay.M

### CODE REVIEW

**Comment by Ananthavijay** [comment]
@aashutoshrathi Yep it is fixed. But I dont know why the travis hasnt started yet. Check my repo

**Comment by Ananthavijay** [comment]
@aashutoshrathi do u have any idea why the travis is not starting its work?

**Comment by Ananthavijay** [comment]
ping @aashutoshrathi

**Comment by Ananthavijay** [comment]
@aashutoshrathi Done!

**Comment by aashutoshrathi** [comment]
Will do soon

**Comment by Ananthavijay** [comment]
Thanks for approving @DipanshKhandelwal 
This is my first ever contribution to iitv. Feels just great

**Pull request merged**
